#! /usr/bin/env bash

# Copyright (C) 2025 Mattéo Rossillol‑‑Laruelle <beatussum@protonmail.com>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <https://www.gnu.org/licenses/>.


set -o pipefail

readonly NAME="${BASH_SOURCE[0]##*/}"

declare -A FLAGS=(
	[destdir]="${PWD}/destdir"
	[patches]="${PWD}/patches"
	[type]="none"
)

########
# CORE #
########

die()
{
	local msg="$*"

	[[ -n "${msg}" ]] || msg="(no message)"
	printf "fatal error: %s\n" "${msg}"
	echo
	echo "with stacktrace:"
	stacktrace

	exit 1
}

stacktrace()
{
	for ((i=0;; ++i)); do
		local file="${BASH_SOURCE[i + 1]}"
		local func="${FUNCNAME[i]}"
		local line="${BASH_LINENO[i]}"

		[[ -f "${file}" ]] || break
		printf "    at %s (%s:%s)\n" "${func}" "$(realpath "${file}")" "${line}"
	done
}

###########
# HELPERS #
###########

build_tarball()
{
	local input_directory="$1"

	case "${FLAGS[type]}" in
		go)
			local vendor="${WORKDIR}/temp/vendor"

			pushd "${input_directory}" &>> /dev/null || die

			local name
			name="$(go_current_module_name)" || die

			go mod vendor -o "${vendor}" || die

			popd &>> /dev/null || die

			pushd "${vendor}/.." &>> /dev/null || die
			tar -ac -f "${FLAGS[destdir]}/${name}.tar.xz" "vendor" || die
			popd &>> /dev/null || die

			;;

		rust)
			local license_mapping="${WORKDIR}/license-mapping.conf"

			if [[ ! -f "${license_mapping}" ]]; then
				wget \
					-O "${license_mapping}" \
					https://gitweb.gentoo.org/repo/gentoo.git/plain/metadata/license-mapping.conf \
					|| die
			fi

			pushd "${WORKDIR}" &>> /dev/null || die

			pycargoebuild -cfM \
				-d "${WORKDIR}/downloaded/crates" \
				-l "${license_mapping}" \
				"${input_directory}" \
				|| die

			popd &>> /dev/null || die

			mv "${WORKDIR}/downloaded/crates"/*-crates.tar.xz "${FLAGS[destdir]}" \
				|| die

			;;

		*)
			die "\`${FLAGS[type]}\` is not a supported type"
			;;
	esac
}

fetch()
{
	local url="$1"

	wget -P "${WORKDIR}/downloaded" "${url}" || die
	tar -xz -f "$(downloaded_filepath "${url}")" -C "${WORKDIR}/unpacked" || die
}

patch() {
	local filepath="$1"

	[[ -d "$(patch_filepath "${filepath}")" ]] || return

	for p in "$(patch_filepath "${filepath}")"/*.patch; do
		pushd "${WORKDIR}/unpacked/${filepath}" &>> /dev/null || die
		command patch -p1 < "${p}" || die
		popd &>> /dev/null || die
	done
}

# getters #

downloaded_filepath()
{
	local url="$1"
	echo "${WORKDIR}/downloaded/${url##*/}"
}

patch_filepath()
{
	local filepath="$1"
	echo "${FLAGS[patches]}/${filepath}"
}

unpacked_filepath()
{
	local filepath="$1"
	tar -tz -f "${filepath}" | head -1 || true
}

unpacked_filepath_from_url()
{
	local url="$1"
	unpacked_filepath "$(downloaded_filepath "${url}")"
}

go_current_module_name()
{
	local name
	name="$(go list)" || die
	echo "${name##*/}"
}

# workdir management #

setup_workdir()
{
	[[ -v WORKDIR  ]] && die
	WORKDIR="$(mktemp -d)" || die
	mkdir "${WORKDIR}"/{downloaded,temp,unpacked} || die
}

cleanup_workdir()
{
	[[ -v WORKDIR  ]] || die
	rm -r "${WORKDIR}" || die
	unset WORKDIR
}

###########
# ACTIONS #
###########

build()
{
	local urls=( "$@" )

	for url in "${urls[@]}"; do
		local unpacked

		fetch "${url}"

		unpacked="$(unpacked_filepath_from_url "${url}")"
		patch "${unpacked}"

		unpacked="${WORKDIR}/unpacked/${unpacked}"
		build_tarball "${unpacked}"
	done
}

usage()
{
	cat << EOF
usage:
  ${NAME} [-d <destination directory>] -t <type> [-] [--] [urls...]

To avoid overcrowding Manifest files and ebuilds, some Rust packages and all Go
packages must provide their dependencies in an external tarball. This little
script automates the process of building these tarballs.

options:
  -d, --destdir <destdir>  Set the destination directory
  -p, --patches <dir>      Set the directory for patches
  -t, --type <type>        Set the type of the underlying projects
  -h, --help               Print this message

${NAME} Copyright (C) 2025 Mattéo Rossillol‑‑Laruelle <beatussum@protonmail.com>
This program comes with ABSOLUTELY NO WARRANTY; for details type \`show w'.
This is free software, and you are welcome to redistribute it
under certain conditions; type \`show c' for details.
EOF
}

########
# MAIN #
########

main()
{
	local -a urls

	while [[ "$#" -ne 0 ]]; do
		case "$1" in
			-d|--destdir)
				FLAGS[destdir]="$2"
				shift

				;;

			-p|--patches)
				FLAGS[patches]="$2"
				shift

				;;

			-t|--type)
				FLAGS[type]="$2"
				shift

				;;

			-h|--help)
				usage
				exit 0

				;;

			-)
				mapfile -t to_append
				urls+=( "${to_append[@]}" )

				;;

			-*)
				usage
				die "\`$1\` is not recognized"

				;;

			--)
				urls+=( "$@" )
				break

				;;

			*)
				urls+=( "$1" )
				;;
		esac

		shift
	done

	[[ "${FLAGS[type]}" = none ]] && die '`--type` must be specified'

	setup_workdir
	mkdir -p "${FLAGS[destdir]}" || die
	build "${urls[@]}"
	cleanup_workdir
}

main "$@"
