name: Build tarballs

on:
  push:
    paths: packages/*

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  build:
    name: Build tarballs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python environment
        uses: actions/setup-python@v5.6.0
        with:
          python-version: ">=3.10"

      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0

      - name: Install pycargoebuild
        run: sudo pip install pycargoebuild

      - name: Build Rust tarballs
        run: ./build -d destdir -t rust - < packages/rust.conf

      - name: Build Go tarballs
        run: ./build -d destdir -t go - < packages/go.conf

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: tarballs
          path: destdir

  reset:
    name: Reset tarballs
    needs: build
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token  }}

    steps:
      - name: Delete existing tag and release
        run: gh release delete latest --cleanup-tag --yes --repo $GITHUB_REPOSITORY
        continue-on-error: true

  release:
    name: Release tarballs
    needs: [build, reset]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download tarballs
        uses: actions/download-artifact@v4.3.0
        with:
          name: tarballs
          path: destdir
      
      - name: Create release
        uses: softprops/action-gh-release@v2.2.2
        with:
          draft: false
          files: destdir/*
          make_latest: true
          prerelease: false
          tag_name: latest
